name: Infrastructure Change
description: Request a change to infrastructure, configuration, or deployment
title: "[INFRA] "
labels: ["infrastructure", "needs-approval"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## Infrastructure Change Request
        Request changes to servers, databases, configurations, deployments, or other infrastructure.

  - type: textarea
    id: change-description
    attributes:
      label: Change Description
      description: What infrastructure change are you proposing?
      placeholder: Clear description of the infrastructure change
    validations:
      required: true

  - type: dropdown
    id: change-type
    attributes:
      label: Change Type
      description: What type of infrastructure change is this?
      options:
        - Server/Cloud configuration
        - Database change
        - Network/Security configuration
        - Deployment pipeline
        - Environment setup
        - Third-party service integration
        - Dependency update
        - Other
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Justification
      description: Why is this change needed?
      placeholder: Explain the business or technical reason for this change
    validations:
      required: true

  - type: dropdown
    id: risk-level
    attributes:
      label: Risk Level
      description: What is the risk level of this change?
      options:
        - High (potential for system downtime or data loss)
        - Medium (may affect performance or availability)
        - Low (minimal impact expected)
    validations:
      required: true

  - type: textarea
    id: affected-systems
    attributes:
      label: Affected Systems
      description: What systems, services, or environments will be affected?
      placeholder: |
        - Production database
        - API servers
        - User authentication service
        etc.
    validations:
      required: true

  - type: textarea
    id: implementation-plan
    attributes:
      label: Implementation Plan
      description: How will this change be implemented?
      placeholder: |
        Step-by-step plan:
        1. Backup current configuration
        2. Apply changes to staging
        3. Test thoroughly
        4. Apply to production during maintenance window
    validations:
      required: true

  - type: textarea
    id: rollback-plan
    attributes:
      label: Rollback Plan
      description: How can this change be reversed if something goes wrong?
      placeholder: Describe the rollback procedure
    validations:
      required: true

  - type: dropdown
    id: downtime-required
    attributes:
      label: Downtime Required?
      description: Will this change require system downtime?
      options:
        - "Yes - estimated downtime required"
        - "No - can be done without downtime"
        - "Unknown - needs assessment"
    validations:
      required: true

  - type: input
    id: maintenance-window
    attributes:
      label: Preferred Maintenance Window
      description: When should this change be made?
      placeholder: "e.g., Saturday 2AM-4AM UTC, or during business hours"

  - type: checkboxes
    id: security-considerations
    attributes:
      label: Security Considerations
      description: Check all that apply
      options:
        - label: This change affects authentication/authorization
        - label: This change affects data encryption
        - label: This change affects network security
        - label: This change affects access controls
        - label: This change affects logging/monitoring
        - label: This change requires security review
        - label: No security implications

  - type: textarea
    id: testing-plan
    attributes:
      label: Testing Plan
      description: How will you verify this change works correctly?
      placeholder: |
        - Test connectivity
        - Verify performance metrics
        - Confirm security controls
        etc.
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      description: Are there any dependencies or prerequisites?
      placeholder: List any dependencies, approvals needed, or prerequisites

  - type: markdown
    attributes:
      value: |
        ---
        ## Change Management Approvals (ISO27001)

  - type: input
    id: approver-tech
    attributes:
      label: Technical Approver
      description: "@mention person who will approve (must be different from implementer)"
      placeholder: "@alice"
    validations:
      required: true

  - type: input
    id: approver-security
    attributes:
      label: Security Approver
      description: "@mention security reviewer (required for Medium/High risk only)"
      placeholder: "@security-lead or N/A if Low risk"

  - type: input
    id: implementer
    attributes:
      label: Implementer
      description: "@mention person who will implement (must be DIFFERENT from approver)"
      placeholder: "@bob"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other relevant information, documentation, or links
      placeholder: Add any additional context, links to documentation, or related issues

  - type: markdown
    attributes:
      value: |
        ---
        ## Post-Implementation (Complete after deployment)

  - type: checkboxes
    id: post-implementation
    attributes:
      label: Post-Implementation Verification
      description: Check all after successful deployment
      options:
        - label: "Change successfully implemented"
        - label: "All systems verified operational"
        - label: "Documentation updated (architecture/network diagrams, runbooks, DR plans, etc.)"
        - label: "BC/DR plans reviewed and updated if needed"

  - type: markdown
    attributes:
      value: |
        ---
        ## Approval Workflow
        1. **Submit** this issue
        2. **Approver(s)** comment "APPROVED ✅" below (or request changes)
        3. **Implementer** executes the change (must be different person from approver)
        4. **Implementer** adds comment with deployment outcome and timestamp
        5. **Check all post-implementation boxes** above
        6. **Close** this issue with summary

        **For audits:** This issue serves as your complete change record with full audit trail.
